# -*- coding: utf-8 -*-
"""Brain_Tumor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188l2HSrpwzngzkIdDdzj97wz6-TSLbPm
"""

!pip install -q git+https://github.com/THU-MIG/yolov10.git

!wget -P -q https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10n.pt

!pip install -q roboflow

from roboflow import Roboflow
rf = Roboflow(api_key = "6HTmCXrvTuYMc6AG2msQ")
project = rf.workspace("brain-mri").project("mri-rskcu")
version = project.version(3)
dataset = version.download("yolov8")

!pip install ultralytics

# Install stable PyTorch + TorchVision that match
!pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121

!pip install ultralytics --upgrade

!yolo task=detect mode=train epochs=25 batch=32 plots=True \
model=yolov10n.pt \
data=/content/MRI-3/data.yaml

from ultralytics import YOLO

# Load your trained model
model_path = "/content/runs/detect/train/weights/best.pt"
model = YOLO(model_path)

# Run inference
results = model.predict(
    source="/content/MRI-3/valid/images",  # folder of images
    conf=0.25,
    save=True
)

import glob
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Get all predicted images (JPG + PNG)
images = glob.glob("/content/runs/detect/predict/*.jpg") + glob.glob("/content/runs/detect/predict/*.png")
images_to_display = images[:10]  # pick first 10

fig, axes = plt.subplots(2, 5, figsize=(20, 10))

for i, ax in enumerate(axes.flat):
    if i < len(images_to_display):
        img = mpimg.imread(images_to_display[i])
        ax.imshow(img)
        ax.set_title(images_to_display[i].split("/")[-1], fontsize=8)
        ax.axis("off")
    else:
        ax.axis("off")

plt.tight_layout()
plt.show()

result = model.predict(source = "/content/MRI-3/valid/images/Tr-glTr_0000_jpg.rf.ee4ad3ca5d0eafd1f482988b89457634.jpg", imgsz = 640, conf = 0.25)
annotated_img = result[0].plot()
annotated_img[:, :, ::-1]

!git config --global user.name "Madhan522"
!git config --global user.email "madhansubramanian2004@gmail.com"

!git branch -M main

!git add .
!git commit -m "Initial commit"





!git remote remove origin

!git config --global user.name "Madhan522"
!git config --global user.email "madhansubramanian2004@gmail.com"

!git init
!git add .
!git commit -m "Upload code and model files"
!git branch -M main

os.environ["GITHUB_TOKEN"] = "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" # replace with fresh token how to upload tokken example

!git remote add origin https://Madhan522:${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}@github.com/Madhan522/Brain_tumor_Detection.git

!git push -u origin main